junit: 4.8.2

gems:
  #- ci_reporter
  - buildr >= 1.4.6

repositories:
  remote:
   - http://repo.fire.dse.vic.gov.au/content/groups/fisg
   - http://www.ibiblio.org/maven2

artifacts:
  easymock: org.easymock:easymock:jar:2.5.2
  gwt_dev: com.google.gwt:gwt-dev:jar:2.3.0 # Due to a bug in 2.3 packaging this is required to be deployed, Fixed in 2.5
  gwt_user: com.google.gwt:gwt-user:jar:2.3.0
  google_guice: com.google.inject:guice:jar:3.0
  google_guice_assistedinject: com.google.inject.extensions:guice-assistedinject:jar:3.0
  aopalliance: aopalliance:aopalliance:jar:1.0 # Required for guice
  gwt_gin: com.google.gwt.inject:gin:jar:1.5.0
  javax_inject: javax.inject:javax.inject:jar:1
  javax_validation: javax.validation:validation-api:jar:1.0.0.GA
  javax_validation_sources: javax.validation:validation-api:jar:sources:1.0.0.GA
  javax_ejb: org.apache.geronimo.specs:geronimo-ejb_3.1_spec:jar:1.0.2
  javax_servlet: org.apache.geronimo.specs:geronimo-servlet_3.0_spec:jar:1.0
  javax_persistence: org.hibernate.javax.persistence:hibernate-jpa-2.0-api:jar:1.0.0.Final
  smartgwt: com.smartgwt:smartgwt:jar:2.5.0
